# Generated by Django 6.1.1 on 2026-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_one_app', '0002_restaurant_coordinates_review_user_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurants/'),
        ),
    ]
